nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5173']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
        expose_headers: ['Authorization']
        max_age: 3600

    paths:
        '^/api/':
            allow_origin: ['http://localhost:5173']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
            max_age: 3600
